import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];
const mobile = matchMedia('(max-width: 900px)').matches;
const reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;

const SPORTS = [
  {name:'Football', category:'Team', accent:0x78f000, kind:'ball', players:'11 / side', place:'Pitch', scoring:'Goals', image:'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=1200&q=80', overview:'The world’s most widely played team sport. Two teams move a spherical ball primarily with the feet, combining spatial awareness, technique, passing and finishing.', equipment:['Football','Boots','Shin guards','Goalkeeper gloves','Goal','Training cones'], clothing:['Jersey','Shorts','Socks','Football boots'], rules:['Two teams compete to score in the opposing goal.','Outfield players may not deliberately handle the ball.','A standard match is divided into two halves.','Offside and fouls shape attacking and defensive play.'], skills:['First touch','Passing','Dribbling','Shooting','Positioning','Tackling'], facts:['Major competitions include the FIFA World Cup and leading domestic leagues.','A full-size pitch is much larger than most indoor team-sport courts.']},
  {name:'Basketball', category:'Team', accent:0xff7a00, kind:'basketball', players:'5 / side', place:'Court', scoring:'2 / 3 pts', image:'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80', overview:'A fast, vertical court sport built around dribbling, passing, shooting and rapid changes between offense and defense.', equipment:['Basketball','Hoop','Backboard','Court markings','Training cones'], clothing:['Jersey','Shorts','Basketball shoes','Compression wear'], rules:['Players advance the ball by passing or dribbling.','Shots can score one, two or three points.','Physical contact is regulated by personal fouls.','Possession is limited by timing rules.'], skills:['Ball handling','Shooting','Passing','Rebounding','Footwork','Defense'], facts:['Basketball was invented in 1891.','The three-point line rewards long-range shooting.']},
  {name:'Volleyball', category:'Team', accent:0x29d2ff, kind:'volleyball', players:'6 / side', place:'Court', scoring:'Rally pts', image:'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80', overview:'A net sport where teams use controlled touches to send a ball over the net and land it inside the opponent’s court.', equipment:['Volleyball','Net','Antennae','Knee pads'], clothing:['Jersey','Shorts','Court shoes','Knee pads'], rules:['A team normally has up to three contacts before returning the ball.','Players rotate positions after winning serve.','A rally ends when the ball lands or a fault occurs.'], skills:['Serve','Pass','Set','Spike','Block','Court awareness'], facts:['Indoor and beach volleyball use different team sizes.','Fast reaction time is central to high-level play.']},
  {name:'Tennis', category:'Racket', accent:0xd9ff36, kind:'racket', players:'1–2 / side', place:'Court', scoring:'15 / 30 / 40', image:'https://images.unsplash.com/photo-1595435742656-5272d0b3fa82?auto=format&fit=crop&w=1200&q=80', overview:'A precision racket sport played in singles or doubles, using spin, placement and movement to control points across a net.', equipment:['Racket','Tennis balls','Net','Court'], clothing:['Tennis shirt','Shorts / skirt','Court shoes','Wristbands'], rules:['The ball must land inside the valid court area.','A player may let the ball bounce once before returning it.','Games, sets and matches use a distinctive scoring system.'], skills:['Serve','Forehand','Backhand','Volley','Footwork','Spin control'], facts:['Major surfaces include hard, clay and grass.','Grand Slam events are the sport’s most famous tournaments.']},
  {name:'Table Tennis', category:'Racket', accent:0x52ffb3, kind:'paddle', players:'1–2 / side', place:'Table', scoring:'11 pts', image:'https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=1200&q=80', overview:'An extremely quick racket sport where spin, timing and reaction speed determine short rallies across a table.', equipment:['Paddle','Ball','Table','Net'], clothing:['Performance shirt','Shorts','Indoor shoes'], rules:['Games are commonly played to 11 points.','The serve alternates after a set number of points.','Spin dramatically changes ball trajectory.'], skills:['Serve variation','Topspin','Backspin','Countering','Fast footwork'], facts:['The lightweight ball can reach very high spin rates.','Close-to-table play demands exceptional reflexes.']},
  {name:'Boxing', category:'Combat', accent:0xff3e3e, kind:'gloves', players:'1 v 1', place:'Ring', scoring:'Rounds', image:'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1200&q=80', overview:'A striking combat sport centered on timing, defense, footwork, conditioning and controlled punches within a regulated ring.', equipment:['Boxing gloves','Heavy bag','Ring','Hand wraps','Mouthguard'], clothing:['Boxing shorts','Boxing shoes','Robe','Protective gear'], rules:['Only legal punches to permitted target areas score.','Bouts are divided into timed rounds.','Officials can stop a contest for safety.'], skills:['Jab','Cross','Hook','Defense','Footwork','Head movement'], facts:['Boxing has both amateur and professional rule sets.','Footwork can be as decisive as punching power.']},
  {name:'Martial Arts', category:'Combat', accent:0xffcc22, kind:'belt', players:'Varies', place:'Dojo / mat', scoring:'Varies', image:'https://images.unsplash.com/photo-1555597673-b21d5c935865?auto=format&fit=crop&w=1200&q=80', overview:'A broad family including karate, taekwondo, judo and MMA, combining technical movement, discipline, tactics and controlled combat.', equipment:['Pads','Gloves','Belts','Protective gear','Training targets'], clothing:['Gi / dobok','Belts','MMA shorts','Rash guard'], rules:['Rules vary by discipline and competition format.','Safety equipment and prohibited techniques differ by style.'], skills:['Balance','Timing','Striking','Grappling','Distance control','Conditioning'], facts:['Martial arts include both striking and grappling systems.','Many styles combine sport competition with traditional practice.']},
  {name:'Swimming', category:'Water', accent:0x00c8ff, kind:'goggles', players:'Individual / relay', place:'Pool', scoring:'Time', image:'https://images.unsplash.com/photo-1530137073520-4ea6e2f10a48?auto=format&fit=crop&w=1200&q=80', overview:'A water sport where efficiency, breathing, body position and stroke mechanics convert power into speed through the pool.', equipment:['Goggles','Swim cap','Lane ropes','Starting block'], clothing:['Swimsuit','Goggles','Swim cap'], rules:['Competitive strokes have specific technique requirements.','Turns and finishes must follow event rules.','Races are won by the fastest valid time.'], skills:['Freestyle','Backstroke','Breaststroke','Butterfly','Starts','Turns'], facts:['Competitive pools use standardized lane dimensions.','Streamlining reduces drag after starts and turns.']},
  {name:'Running', category:'Individual', accent:0xf3ff4b, kind:'shoe', players:'Individual', place:'Track / road', scoring:'Time', image:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1200&q=80', overview:'Running spans sprinting, middle distance, road racing and endurance events, all built on efficient mechanics and energy management.', equipment:['Running shoes','Starting blocks','Timing system','Track'], clothing:['Singlet','Shorts','Running shoes','Compression gear'], rules:['Track events use lanes or shared racing lines depending on distance.','False-start and course rules vary by event.'], skills:['Stride efficiency','Pacing','Acceleration','Endurance','Race tactics'], facts:['Sprint and endurance training demand very different energy systems.','Shoe design can influence grip, cushioning and energy return.']},
  {name:'Cycling', category:'Individual', accent:0x00ffa6, kind:'bike', players:'Individual / team', place:'Road / track', scoring:'Time / points', image:'https://images.unsplash.com/photo-1541625602330-2277a4c46182?auto=format&fit=crop&w=1200&q=80', overview:'A speed and endurance sport where aerodynamics, power delivery, bike handling and tactics interact across road, track and off-road disciplines.', equipment:['Bicycle','Helmet','Cycling computer','Repair kit'], clothing:['Jersey','Bib shorts','Helmet','Gloves','Cycling shoes'], rules:['Rules vary across road, track, BMX and mountain disciplines.','Drafting and course position strongly affect race tactics.'], skills:['Cadence','Cornering','Climbing','Descending','Bike handling'], facts:['Aerodynamic drag becomes increasingly important at higher speeds.','Professional road racing often uses team tactics.']},
  {name:'Motorsport', category:'Motorsport', accent:0xff244f, kind:'helmet', players:'Driver', place:'Circuit', scoring:'Time / points', image:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80', overview:'Circuit racing combines vehicle performance with driver precision, braking, racing lines, tire management, reaction speed and safety systems.', equipment:['Racing helmet','Steering wheel','Race car','HANS device','Fire extinguisher'], clothing:['Racing suit','Gloves','Racing shoes','Balaclava','Helmet'], rules:['Drivers follow flag, track-limit and safety procedures.','Race formats can be based on laps, time or stages.','Technical regulations define vehicle eligibility.'], skills:['Braking','Racing line','Throttle control','Racecraft','Situational awareness'], facts:['Protective equipment is engineered for fire and impact resistance.','Tire temperature and grip are major performance variables.']},
  {name:'Gym / Bodybuilding', category:'Strength', accent:0xff7a33, kind:'dumbbell', players:'Individual', place:'Gym', scoring:'Physique / reps', image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80', overview:'Strength training develops force, muscle, movement quality and conditioning through progressive resistance and structured exercise.', equipment:['Dumbbells','Barbell','Weight plates','Bench','Cable machine'], clothing:['Training shirt','Shorts','Training shoes','Lifting straps'], rules:['Training should use controlled technique and suitable loading.','Bodybuilding competitions evaluate physique rather than lifted weight.'], skills:['Technique','Progressive overload','Mobility','Recovery','Exercise selection'], facts:['Strength gains involve both neural and muscular adaptation.','Rest and nutrition strongly influence training outcomes.']},
  {name:'Weightlifting', category:'Strength', accent:0xffb13b, kind:'barbell', players:'Individual', place:'Platform', scoring:'Total kg', image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=80', overview:'Olympic weightlifting is built around the snatch and the clean & jerk, demanding explosive power, mobility and precise technique.', equipment:['Olympic barbell','Bumper plates','Platform','Chalk'], clothing:['Lifting singlet','Lifting shoes','Belt','Knee sleeves'], rules:['Successful attempts must meet technical standards.','Athletes receive multiple attempts in each lift.'], skills:['Snatch','Clean','Jerk','Front squat','Pulling power','Mobility'], facts:['The two competition lifts are highly technical full-body movements.','Specialized shoes provide a stable raised heel.']},
  {name:'Golf', category:'Individual', accent:0x67df64, kind:'golf', players:'Individual', place:'Course', scoring:'Strokes', image:'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80', overview:'A precision sport where players use different clubs to move a ball through a course in as few strokes as possible.', equipment:['Golf clubs','Golf ball','Golf bag','Tees'], clothing:['Polo shirt','Golf trousers / shorts','Golf shoes','Cap'], rules:['Lower stroke totals are better.','Different clubs are chosen for distance, trajectory and lie.'], skills:['Driving','Iron play','Chipping','Putting','Course management'], facts:['A standard full course commonly has 18 holes.','Wind and terrain can significantly alter shot strategy.']},
  {name:'Baseball', category:'Team', accent:0xff5345, kind:'baseball', players:'9 / side', place:'Diamond', scoring:'Runs', image:'https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&w=1200&q=80', overview:'A bat-and-ball team sport built around pitching, hitting, base running and fielding across alternating offensive and defensive innings.', equipment:['Baseball','Bat','Glove','Helmet','Bases'], clothing:['Uniform','Cap','Cleats','Batting gloves'], rules:['Teams alternate between batting and fielding.','Runs score by safely advancing around the bases.','Three outs end a team’s turn at bat.'], skills:['Hitting','Pitching','Throwing','Catching','Base running'], facts:['Pitch types vary by speed, movement and grip.','Field positions have highly specialized responsibilities.']},
  {name:'American Football', category:'Team', accent:0x4ac3ff, kind:'football-us', players:'11 / side', place:'Field', scoring:'Touchdowns', image:'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80', overview:'A territorial contact team sport built around set plays, passing, running, blocking and strategic field position.', equipment:['Football','Helmet','Shoulder pads','Goalposts'], clothing:['Jersey','Pants','Helmet','Cleats','Pads'], rules:['Teams advance the ball in a limited series of downs.','Touchdowns and field goals are primary scoring methods.'], skills:['Throwing','Catching','Blocking','Tackling','Route running','Play recognition'], facts:['Offense, defense and special teams use different personnel groups.','Protective equipment is central to the sport.']},
  {name:'Ice Hockey', category:'Team', accent:0x89d9ff, kind:'hockey', players:'6 on ice', place:'Rink', scoring:'Goals', image:'https://images.unsplash.com/photo-1515703407324-5f753afd8be8?auto=format&fit=crop&w=1200&q=80', overview:'A fast contact ice sport where skaters use sticks to move a puck and create scoring chances while transitioning rapidly between zones.', equipment:['Hockey stick','Puck','Helmet','Skates','Goal'], clothing:['Jersey','Hockey pants','Helmet','Pads','Skates'], rules:['Teams try to shoot the puck into the opponent’s net.','Offside, icing and penalties shape possession.'], skills:['Skating','Stickhandling','Passing','Shooting','Checking'], facts:['Line changes can happen while play continues.','Goalies use specialized protective equipment.']},
  {name:'Skiing', category:'Winter', accent:0xdff6ff, kind:'ski', players:'Individual', place:'Snow', scoring:'Time / points', image:'https://images.unsplash.com/photo-1529669851596-ba9a5549af95?auto=format&fit=crop&w=1200&q=80', overview:'Skiing includes alpine, cross-country and freestyle disciplines, balancing edge control, terrain reading and body position on snow.', equipment:['Skis','Poles','Goggles','Helmet'], clothing:['Ski jacket','Ski pants','Gloves','Helmet','Goggles'], rules:['Competition rules depend on the discipline.','Gates, time or judged execution may determine results.'], skills:['Edge control','Balance','Carving','Terrain awareness','Speed control'], facts:['Ski construction is tailored to terrain and event type.','Wax and snow conditions affect glide.']},
  {name:'Snowboarding', category:'Winter', accent:0xa4e4ff, kind:'board', players:'Individual', place:'Snow', scoring:'Time / points', image:'https://images.unsplash.com/photo-1522056615691-da7b8106c665?auto=format&fit=crop&w=1200&q=80', overview:'A winter board sport blending carving, balance and aerial control across piste, park and racing formats.', equipment:['Snowboard','Bindings','Helmet','Goggles'], clothing:['Snow jacket','Snow pants','Boots','Gloves','Helmet'], rules:['Events may be judged on execution or decided by time.','Bindings secure both feet to a single board.'], skills:['Carving','Edge transitions','Jumps','Balance','Terrain reading'], facts:['Board shape and flex vary by riding style.','Freestyle and alpine setups can be very different.']},
  {name:'Skateboarding', category:'Extreme', accent:0xffdf55, kind:'skate', players:'Individual', place:'Street / park', scoring:'Judged', image:'https://images.unsplash.com/photo-1520045892732-304bc3ac5d8e?auto=format&fit=crop&w=1200&q=80', overview:'A board sport driven by balance, creativity and technical trick execution across street obstacles, ramps and bowls.', equipment:['Skateboard','Helmet','Knee pads','Elbow pads'], clothing:['Skate shoes','Casual sportswear','Helmet'], rules:['Competition formats judge difficulty, execution and consistency.','Street and park use different obstacle environments.'], skills:['Ollie','Flip tricks','Grinding','Transition riding','Balance'], facts:['Skateboard trucks control turning response.','Wheel hardness influences grip and ride feel.']},
  {name:'Surfing', category:'Water', accent:0x2ae7d2, kind:'surf', players:'Individual', place:'Ocean', scoring:'Judged', image:'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1200&q=80', overview:'A wave-riding sport where timing, paddling, balance and line choice turn moving ocean energy into speed and maneuverability.', equipment:['Surfboard','Leash','Wax'], clothing:['Wetsuit','Rash guard'], rules:['Competition scoring rewards quality, difficulty and execution on selected waves.','Priority rules manage which surfer may take a wave.'], skills:['Paddling','Takeoff','Bottom turn','Carving','Wave reading'], facts:['Board dimensions are chosen around rider, wave and style.','Wave selection can be as important as maneuver difficulty.']},
  {name:'Archery', category:'Individual', accent:0xff9445, kind:'bow', players:'Individual', place:'Range', scoring:'Target rings', image:'https://images.unsplash.com/photo-1510925758641-869d353cecc7?auto=format&fit=crop&w=1200&q=80', overview:'A precision sport using a bow and arrows, combining repeatable form, focus, breath control and fine aiming adjustments.', equipment:['Bow','Arrows','Target','Quiver','Arm guard'], clothing:['Close-fitting top','Arm guard','Finger tab'], rules:['Arrows score according to where they land on the target.','Distances and bow classes vary by event.'], skills:['Stance','Anchor point','Release','Aiming','Breath control'], facts:['Tiny consistency errors can move arrows significantly at long range.','Recurve archery is an Olympic discipline.']},
  {name:'Fencing', category:'Combat', accent:0xd4e8ff, kind:'fencing', players:'1 v 1', place:'Piste', scoring:'Touches', image:'https://images.unsplash.com/photo-1552072092-7f9b8d63efcb?auto=format&fit=crop&w=1200&q=80', overview:'A rapid combat sport using foil, épée or sabre, built around distance, timing, blade control and explosive footwork.', equipment:['Weapon','Mask','Body cord','Scoring apparatus'], clothing:['Fencing jacket','Breeches','Glove','Mask'], rules:['Valid target areas differ by weapon.','Electronic systems record valid touches.'], skills:['Lunge','Parry','Riposte','Distance control','Blade work'], facts:['Foil, épée and sabre use different tactical rules.','Fencing exchanges can unfold in fractions of a second.']},
  {name:'Wrestling', category:'Combat', accent:0xff5d6c, kind:'wrestling', players:'1 v 1', place:'Mat', scoring:'Points / fall', image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80', overview:'A grappling combat sport focused on takedowns, control, exposure and positional dominance without striking.', equipment:['Wrestling mat','Headgear (where used)','Training dummies'], clothing:['Singlet','Wrestling shoes','Knee pads'], rules:['Points reward takedowns and control.','A pin or fall can end the bout.','Legal grips depend on wrestling style.'], skills:['Takedowns','Sprawls','Throws','Mat control','Conditioning'], facts:['Freestyle and Greco-Roman emphasize different techniques.','Leverage and timing can overcome size differences.']},
  {name:'Badminton', category:'Racket', accent:0x8bff7a, kind:'shuttle', players:'1–2 / side', place:'Court', scoring:'21 pts', image:'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1200&q=80', overview:'A lightweight racket sport using a shuttlecock, combining explosive movement, deceptive strokes and extremely fast exchanges.', equipment:['Badminton racket','Shuttlecock','Net'], clothing:['Performance shirt','Shorts / skirt','Court shoes'], rules:['Games are normally played to 21 points.','The shuttle must pass over the net into the valid court.'], skills:['Serve','Clear','Drop','Smash','Net play','Footwork'], facts:['The shuttle slows rapidly because of high aerodynamic drag.','Elite rallies demand repeated explosive direction changes.']},
  {name:'Climbing', category:'Extreme', accent:0xffa23a, kind:'climb', players:'Individual', place:'Wall / rock', scoring:'Height / tops', image:'https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1200&q=80', overview:'Sport climbing challenges grip, movement efficiency, problem solving and composure on walls and routes of increasing difficulty.', equipment:['Harness','Rope','Carabiners','Climbing shoes','Chalk'], clothing:['Flexible sportswear','Climbing shoes','Harness'], rules:['Rules vary across lead, speed and bouldering.','Safety systems differ by discipline.'], skills:['Footwork','Grip efficiency','Route reading','Body positioning','Power endurance'], facts:['Bouldering uses short routes and padded landing zones.','Climbing shoes prioritize precision and friction.']}
];

const categoryMap={All:'All',Team:'Team',Combat:'Combat',Racket:'Racket',Water:'Water',Motorsport:'Motorsport',Winter:'Winter',Strength:'Strength'};
let renderer,scene,camera,controls,clock,raycaster,pointer,arenaGroup,sportsGroup;
let hoverObj=null,selectedObj=null,currentSport=null,currentTab='overview';
let cameraTarget=new THREE.Vector3(0,1.2,0),desiredCam=new THREE.Vector3(0,8.5,16.5),activeCategory='All';
let dragInspect=false,lastPointerX=0,ready=false,soundOn=false,audioCtx=null;
const interactive=[];

function supportsWebGL(){try{const c=document.createElement('canvas');return !!(window.WebGLRenderingContext&&(c.getContext('webgl2')||c.getContext('webgl')))}catch{return false}}
if(!supportsWebGL()){ $('#webgl-fallback').hidden=false;$('#loading').hidden=true;throw new Error('WebGL unavailable') }
init();

function init(){
  renderer=new THREE.WebGLRenderer({canvas:$('#scene'),antialias:!mobile,alpha:false,powerPreference:'high-performance'});
  renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.35:2));renderer.shadowMap.enabled=!mobile;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
  scene=new THREE.Scene();scene.background=new THREE.Color(0x05070a);scene.fog=new THREE.FogExp2(0x05070a,.017);
  camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,120);camera.position.copy(desiredCam);clock=new THREE.Clock();raycaster=new THREE.Raycaster();pointer=new THREE.Vector2(9,9);
  controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.enablePan=false;controls.minDistance=8;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.48;controls.minPolarAngle=Math.PI*.2;controls.target.copy(cameraTarget);
  arenaGroup=new THREE.Group();sportsGroup=new THREE.Group();scene.add(arenaGroup,sportsGroup);makeLights();makeArena();makeSports();makeParticles();bindUI();$('#sport-count').textContent=SPORTS.length;simulateLoading();animate();
}

function makeLights(){scene.add(new THREE.HemisphereLight(0x8fb6d9,0x090a0c,.65));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(3,10,7);key.castShadow=!mobile;key.shadow.mapSize.set(mobile?512:1024,mobile?512:1024);scene.add(key);const rim=new THREE.DirectionalLight(0x3d8dff,1.3);rim.position.set(-7,4,-8);scene.add(rim);const neon=new THREE.PointLight(0x78f000,18,20,2);neon.position.set(0,3,-1);scene.add(neon)}
function mat(color,metal=.55,rough=.32,emissive=0x000000){return new THREE.MeshStandardMaterial({color,metalness:metal,roughness:rough,emissive,emissiveIntensity:.25})}
function mesh(g,m,pos=[0,0,0]){const o=new THREE.Mesh(g,m);o.position.set(...pos);o.castShadow=!mobile;o.receiveShadow=!mobile;return o}

function makeArena(){
  const floor=mesh(new THREE.CylinderGeometry(15.7,15.7,.28,96),new THREE.MeshStandardMaterial({color:0x0b0e12,metalness:.72,roughness:.21}),[0,-.25,0]);arenaGroup.add(floor);
  const inner=mesh(new THREE.CylinderGeometry(11.1,11.1,.035,96),new THREE.MeshStandardMaterial({color:0x10151b,metalness:.6,roughness:.28}),[0,-.06,0]);arenaGroup.add(inner);
  const ring=mesh(new THREE.TorusGeometry(13.35,.055,10,128),new THREE.MeshStandardMaterial({color:0x78f000,emissive:0x78f000,emissiveIntensity:2.4}),[0,.02,0]);ring.rotation.x=Math.PI/2;arenaGroup.add(ring);
  const ring2=mesh(new THREE.TorusGeometry(10.35,.025,8,128),new THREE.MeshStandardMaterial({color:0x2a3d4d,emissive:0x1d3445,emissiveIntensity:.8}),[0,.01,0]);ring2.rotation.x=Math.PI/2;arenaGroup.add(ring2);
  for(let i=0;i<32;i++){const a=i/32*Math.PI*2,r=14.45;const post=mesh(new THREE.BoxGeometry(.08,2.6,.08),mat(i%4===0?0x78f000:0x25303a,.65,.35,i%4===0?0x78f000:0x000000),[Math.cos(a)*r,1.05,Math.sin(a)*r]);post.rotation.y=-a;arenaGroup.add(post)}
  for(let i=0;i<8;i++){const a=i/8*Math.PI*2,r=12.2;const light=new THREE.SpotLight(i%2?0x9ad7ff:0xffffff,90,18,.46,.6,1.7);light.position.set(Math.cos(a)*r,7.3,Math.sin(a)*r);light.target.position.set(Math.cos(a)*5,0,Math.sin(a)*5);scene.add(light,light.target);const housing=mesh(new THREE.BoxGeometry(.7,.3,.45),mat(0x1a2026,.85,.2),[Math.cos(a)*r,7.3,Math.sin(a)*r]);housing.lookAt(0,0,0);arenaGroup.add(housing)}
  const center=mesh(new THREE.CylinderGeometry(2.2,2.45,.46,48),mat(0x141a21,.75,.22),[0,.08,0]);arenaGroup.add(center);const centerRing=mesh(new THREE.TorusGeometry(2.18,.055,8,96),new THREE.MeshStandardMaterial({color:0x78f000,emissive:0x78f000,emissiveIntensity:3}),[0,.33,0]);centerRing.rotation.x=Math.PI/2;arenaGroup.add(centerRing);
  const logoCanvas=document.createElement('canvas');logoCanvas.width=1024;logoCanvas.height=256;const ctx=logoCanvas.getContext('2d');ctx.fillStyle='#78f000';ctx.font='900 122px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('SAEID SPORTS',512,128);const tex=new THREE.CanvasTexture(logoCanvas);tex.colorSpace=THREE.SRGBColorSpace;const banner=mesh(new THREE.PlaneGeometry(8,2),new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:.9}),[0,4.9,-12.8]);arenaGroup.add(banner)
}

function buildIcon(s){
  const g=new THREE.Group(),c=s.accent,main=mat(c,.4,.34),dark=mat(0x151a20,.65,.28),white=mat(0xf0f4f7,.2,.35),metal=mat(0xaab5c0,.92,.16);const sphere=(r=.65,m=main)=>mesh(new THREE.SphereGeometry(r,28,20),m);
  switch(s.kind){
    case 'ball':{const b=sphere(.72,white);for(let i=0;i<8;i++){const p=mesh(new THREE.CircleGeometry(.11,5),new THREE.MeshStandardMaterial({color:0x111417,roughness:.6}),[0,0,.72]);p.rotation.z=i*.78;b.add(p)}g.add(b);break}
    case 'basketball':{const b=sphere(.74,mat(0xd85c14,.05,.74));[0,Math.PI/2].forEach(r=>{const t=mesh(new THREE.TorusGeometry(.745,.018,8,48),mat(0x141414,.1,.7));t.rotation.set(r,0,0);b.add(t)});const t=mesh(new THREE.TorusGeometry(.745,.018,8,48),mat(0x141414,.1,.7));t.rotation.y=Math.PI/2;b.add(t);g.add(b);break}
    case 'volleyball':{const b=sphere(.72,white),stripe=mesh(new THREE.TorusGeometry(.71,.065,10,48),main);stripe.rotation.x=Math.PI/2;b.add(stripe);g.add(b);break}
    case 'racket':{const head=mesh(new THREE.TorusGeometry(.55,.07,12,40),dark,[0,.35,0]);head.scale.y=1.25;const handle=mesh(new THREE.CylinderGeometry(.07,.08,.9,12),main,[0,-.55,0]);g.add(head,handle);break}
    case 'paddle':{const face=mesh(new THREE.CylinderGeometry(.52,.52,.08,32),main,[0,.22,0]);face.rotation.x=Math.PI/2;face.scale.y=1.1;const h=mesh(new THREE.BoxGeometry(.18,.7,.12),dark,[0,-.5,0]);g.add(face,h);break}
    case 'gloves':{for(const x of [-.38,.38]){const glove=sphere(.46,main);glove.position.set(x,.15,0);glove.scale.set(1,.82,.9);const cuff=mesh(new THREE.CylinderGeometry(.3,.34,.38,18),dark,[x,-.35,0]);g.add(glove,cuff)}break}
    case 'belt':{const band=mesh(new THREE.TorusGeometry(.62,.1,10,36),main);band.scale.y=.55;const buckle=mesh(new THREE.BoxGeometry(.36,.28,.12),metal,[0,0,.58]);g.add(band,buckle);break}
    case 'goggles':{for(const x of [-.35,.35]){const lens=mesh(new THREE.CylinderGeometry(.34,.34,.08,24),new THREE.MeshPhysicalMaterial({color:0x56d7ff,metalness:.1,roughness:.08,transmission:.28,transparent:true,opacity:.82}),[x,0,0]);lens.rotation.x=Math.PI/2;g.add(lens)}g.add(mesh(new THREE.BoxGeometry(.25,.07,.07),dark));break}
    case 'shoe':{const shoe=mesh(new THREE.BoxGeometry(1.3,.45,.55),main,[.1,0,0]);shoe.geometry.translate(.15,0,0);shoe.rotation.z=-.08;const sole=mesh(new THREE.BoxGeometry(1.4,.13,.58),white,[.1,-.27,0]);g.add(shoe,sole);break}
    case 'bike':{for(const x of [-.72,.72]){const w=mesh(new THREE.TorusGeometry(.52,.055,8,32),dark,[x,-.15,0]);w.rotation.y=Math.PI/2;g.add(w)}const f1=mesh(new THREE.CylinderGeometry(.04,.04,1.25,8),main);f1.rotation.z=Math.PI/3;const f2=f1.clone();f2.rotation.z=-Math.PI/3;g.add(f1,f2);break}
    case 'helmet':{const h=mesh(new THREE.SphereGeometry(.72,32,22,0,Math.PI*2,0,Math.PI*.66),new THREE.MeshPhysicalMaterial({color:c,metalness:.35,roughness:.18,clearcoat:1,clearcoatRoughness:.08}));h.rotation.x=Math.PI;const visor=mesh(new THREE.BoxGeometry(.95,.26,.08),new THREE.MeshPhysicalMaterial({color:0x0a1720,metalness:.6,roughness:.05,transmission:.18,transparent:true,opacity:.8}),[0,.05,.64]);g.add(h,visor);break}
    case 'dumbbell':{const bar=mesh(new THREE.CylinderGeometry(.07,.07,1.45,14),metal);bar.rotation.z=Math.PI/2;g.add(bar);for(const x of [-.63,.63])for(const o of [-.09,.09]){const w=mesh(new THREE.CylinderGeometry(.31,.31,.16,22),dark,[x+o,0,0]);w.rotation.z=Math.PI/2;g.add(w)}break}
    case 'barbell':{const bar=mesh(new THREE.CylinderGeometry(.045,.045,1.8,12),metal);bar.rotation.z=Math.PI/2;g.add(bar);for(const x of [-.72,.72]){const p=mesh(new THREE.CylinderGeometry(.37,.37,.18,24),main,[x,0,0]);p.rotation.z=Math.PI/2;g.add(p)}break}
    case 'golf':{const ball=sphere(.28,white);ball.position.set(.45,-.2,.1);const shaft=mesh(new THREE.CylinderGeometry(.025,.03,1.35,8),metal,[-.25,.1,0]);shaft.rotation.z=-.18;const club=mesh(new THREE.BoxGeometry(.4,.14,.16),dark,[-.1,-.58,0]);g.add(ball,shaft,club);break}
    case 'baseball':{const ball=sphere(.43,white),bat=mesh(new THREE.CylinderGeometry(.08,.16,1.45,16),main,[.48,0,0]);bat.rotation.z=-.55;g.add(ball,bat);break}
    case 'football-us':{const b=mesh(new THREE.SphereGeometry(.68,28,18),mat(0x7b3d22,.1,.72));b.scale.set(1.25,.72,.72);b.rotation.z=-.18;b.add(mesh(new THREE.BoxGeometry(.38,.05,.06),white,[0,.52,.15]));g.add(b);break}
    case 'hockey':{const puck=mesh(new THREE.CylinderGeometry(.36,.36,.13,28),dark,[.3,-.35,.2]),stick=mesh(new THREE.BoxGeometry(.12,1.45,.12),main,[-.3,.1,0]),blade=mesh(new THREE.BoxGeometry(.55,.13,.15),main,[0,-.57,0]);stick.rotation.z=.35;g.add(puck,stick,blade);break}
    case 'ski':{for(const x of [-.28,.28]){const ski=mesh(new THREE.BoxGeometry(.14,1.7,.08),main,[x,0,0]);ski.rotation.x=.08;g.add(ski)}break}
    case 'board':{const b=mesh(new THREE.BoxGeometry(.55,1.65,.1),main);b.rotation.z=.18;g.add(b);break}
    case 'skate':{const deck=mesh(new THREE.BoxGeometry(1.4,.18,.42),main,[0,.1,0]);for(const x of [-.5,.5])for(const z of [-.25,.25]){const w=mesh(new THREE.CylinderGeometry(.09,.09,.08,12),white,[x,-.11,z]);w.rotation.x=Math.PI/2;g.add(w)}g.add(deck);break}
    case 'surf':{const b=mesh(new THREE.CapsuleGeometry(.28,1.35,6,18),main);b.scale.set(.35,1,.12);b.rotation.z=Math.PI/2;g.add(b);break}
    case 'bow':{const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(0,-.85,0),new THREE.Vector3(.28,-.4,0),new THREE.Vector3(.34,0,0),new THREE.Vector3(.28,.4,0),new THREE.Vector3(0,.85,0)]);g.add(mesh(new THREE.TubeGeometry(curve,40,.045,8,false),main),mesh(new THREE.CylinderGeometry(.01,.01,1.7,6),white));break}
    case 'fencing':{const blade=mesh(new THREE.CylinderGeometry(.018,.025,1.35,8),metal,[0,.1,0]),guard=mesh(new THREE.SphereGeometry(.22,18,10,0,Math.PI*2,0,Math.PI/2),main,[0,-.58,0]),grip=mesh(new THREE.CylinderGeometry(.055,.07,.38,10),dark,[0,-.84,0]);guard.rotation.x=Math.PI;g.add(blade,guard,grip);break}
    case 'wrestling':{const ring=mesh(new THREE.TorusGeometry(.65,.14,12,32),main);ring.scale.y=.6;g.add(ring);break}
    case 'shuttle':{const head=sphere(.22,white);head.position.y=-.35;for(let i=0;i<8;i++){const feather=mesh(new THREE.CylinderGeometry(.025,.055,.68,6),white);feather.position.y=.1;feather.rotation.z=i%2?.22:-.22;feather.rotation.y=i*Math.PI/4;g.add(feather)}g.add(head);break}
    case 'climb':{const wall=mesh(new THREE.BoxGeometry(1.3,1.5,.25),dark);for(let i=0;i<7;i++){const hold=sphere(.11,mat(i%2?c:0xff4e72,.2,.6));hold.scale.set(1.3,.7,.6);hold.position.set((i%3-.9)*.38,(Math.floor(i/3)-.6)*.45,.18);wall.add(hold)}g.add(wall);break}
    default:g.add(sphere())
  }return g
}

function makeSports(){
  SPORTS.forEach((s,i)=>{const a=i/SPORTS.length*Math.PI*2-.45,r=i%2?10.75:12.65,group=new THREE.Group();group.userData={sport:s,index:i,baseScale:1,angle:a};group.position.set(Math.cos(a)*r,.72,Math.sin(a)*r);const podium=mesh(new THREE.CylinderGeometry(.95,1.12,.25,28),mat(0x121820,.72,.2),[0,-.55,0]);const glow=mesh(new THREE.TorusGeometry(.92,.035,7,48),new THREE.MeshStandardMaterial({color:s.accent,emissive:s.accent,emissiveIntensity:2.2}),[0,-.42,0]);glow.rotation.x=Math.PI/2;const icon=buildIcon(s);icon.name='icon';icon.scale.setScalar(i%5===0?.88:1);group.add(podium,glow,icon);const hit=mesh(new THREE.SphereGeometry(1.05,12,8),new THREE.MeshBasicMaterial({transparent:true,opacity:0}),[0,.08,0]);hit.userData.parentSport=group;group.add(hit);interactive.push(hit);const beacon=new THREE.PointLight(s.accent,5.5,4,2);beacon.position.set(0,.25,0);group.add(beacon);group.userData.beacon=beacon;sportsGroup.add(group)})
}
function makeParticles(){const n=mobile?220:620,pos=new Float32Array(n*3);for(let i=0;i<n;i++){const r=8+Math.random()*18,a=Math.random()*Math.PI*2;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=Math.random()*8;pos[i*3+2]=Math.sin(a)*r}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));const points=new THREE.Points(geo,new THREE.PointsMaterial({size:.018,color:0x8fa3b5,transparent:true,opacity:.28,depthWrite:false}));scene.add(points);points.userData.particles=true}

function bindUI(){
  addEventListener('resize',onResize);renderer.domElement.addEventListener('pointermove',onPointerMove);renderer.domElement.addEventListener('pointerdown',onPointerDown);renderer.domElement.addEventListener('pointerup',()=>dragInspect=false);renderer.domElement.addEventListener('click',onClick);
  $('#enter-arena').onclick=endIntro;$('#skip-intro').onclick=endIntro;$('#open-search').onclick=()=>openOverlay('search');$('#close-search').onclick=()=>openOverlay();$('#help-toggle').onclick=()=>openOverlay('help');$('#close-help').onclick=()=>openOverlay();$('#close-detail').onclick=backToHall;$('#back-btn').onclick=backToHall;$('#sound-toggle').onclick=toggleSound;
  $$('.category-chip').forEach(b=>b.onclick=()=>filterCategory(b.dataset.category));$$('.tab').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;$$('.tab').forEach(x=>x.classList.toggle('active',x===b));renderTab()});$('#search-input').addEventListener('input',renderSearch);renderSearch();addEventListener('keydown',e=>{if(e.key==='Escape'){if(currentSport)backToHall();else openOverlay()}if(e.key==='/'&&!e.metaKey&&!e.ctrlKey){e.preventDefault();openOverlay('search')}})
}
function simulateLoading(){let p=0;const t=setInterval(()=>{p=Math.min(96,p+Math.max(1,Math.random()*9));setProgress(p);if(p>=96){clearInterval(t);setTimeout(()=>{setProgress(100);ready=true;setTimeout(()=>{$('#loading').classList.add('done');$('#intro').hidden=false},320)},350)}},110)}
function setProgress(p){$('#progress-bar').style.width=p+'%';$('#progress-label').textContent=Math.round(p)+'%'}
function endIntro(){playUi(.03,220);$('#intro').classList.add('leaving');setTimeout(()=>{$('#intro').hidden=true},900)}
function onPointerMove(e){pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;$('#pointer-label').style.left=e.clientX+'px';$('#pointer-label').style.top=e.clientY+'px';if(currentSport&&dragInspect&&selectedObj){const dx=e.clientX-lastPointerX;selectedObj.rotation.y+=dx*.008;lastPointerX=e.clientX}}
function onPointerDown(e){if(currentSport){dragInspect=true;lastPointerX=e.clientX}}
function onClick(){if(!ready||currentSport)return;if(hoverObj)selectSport(hoverObj.userData.parentSport)}

function selectSport(group){
  currentSport=group.userData.sport;selectedObj=group;playUi(.045,520);$('#hero-hud').classList.add('hidden');$('#detail-panel').classList.add('open');$('#detail-panel').setAttribute('aria-hidden','false');$('#detail-category').textContent=currentSport.category.toUpperCase()+' SPORT';$('#detail-name').textContent=currentSport.name.toUpperCase();currentTab='overview';$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab==='overview'));renderTab();const p=group.position.clone(),dir=p.clone().normalize();cameraTarget.copy(p).add(new THREE.Vector3(0,.25,0));desiredCam.copy(p.clone().add(dir.multiplyScalar(mobile?5.4:4.8))).add(new THREE.Vector3(0,mobile?2.2:2.6,0));controls.enabled=false;sportsGroup.children.forEach(o=>o.userData.targetOpacity=o===group?1:.14)
}
function backToHall(){if(!currentSport)return;playUi(.03,180);currentSport=null;selectedObj=null;$('#detail-panel').classList.remove('open');$('#detail-panel').setAttribute('aria-hidden','true');$('#hero-hud').classList.remove('hidden');desiredCam.set(0,8.5,16.5);cameraTarget.set(0,1.2,0);setTimeout(()=>controls.enabled=true,750);sportsGroup.children.forEach(o=>o.userData.targetOpacity=1)}

function renderTab(){
  if(!currentSport)return;const s=currentSport,c=$('#tab-content');
  if(currentTab==='overview')c.innerHTML=`<p class="panel-copy">${s.overview}</p><div class="info-stats"><div class="stat"><b>${s.players}</b><span>PLAYERS</span></div><div class="stat"><b>${s.place}</b><span>ARENA</span></div><div class="stat"><b>${s.scoring}</b><span>SCORING</span></div></div><div class="photo-card"><img loading="lazy" decoding="async" src="${s.image}" alt="${s.name} sports environment" onerror="this.style.display='none';this.parentElement.style.background='radial-gradient(circle at 30% 30%, #24303c, #0b0f14)'"><span>REAL WORLD / ${s.name.toUpperCase()}</span></div><p class="panel-copy">Select the equipment and clothing tabs to explore the objects used in this sport.</p>`;
  else if(currentTab==='equipment')c.innerHTML=`<p class="panel-copy">Select an item to highlight the 3D display and focus on its role.</p><div class="item-grid">${s.equipment.map((x,i)=>`<button class="item" data-item="${i}"><b>${x}</b><span>${equipmentPurpose(x,s.name)}</span></button>`).join('')}</div>`;
  else if(currentTab==='clothing')c.innerHTML=`<p class="panel-copy">Performance apparel is shaped by movement, climate, safety and the surface of play.</p><div class="item-grid">${s.clothing.map((x,i)=>`<button class="item" data-wear="${i}"><b>${x}</b><span>${wearPurpose(x)}</span></button>`).join('')}</div>`;
  else if(currentTab==='rules')c.innerHTML=`<ul class="list-clean">${s.rules.map(x=>`<li>${x}</li>`).join('')}</ul>`;
  else if(currentTab==='skills')c.innerHTML=`<div class="item-grid">${s.skills.map(x=>`<div class="item"><b>${x}</b><span>Key performance skill</span></div>`).join('')}</div>`;
  else c.innerHTML=`<ul class="list-clean">${s.facts.map(x=>`<li>${x}</li>`).join('')}</ul>`;
  c.querySelectorAll('[data-item],[data-wear]').forEach(btn=>btn.onclick=()=>{playUi(.025,360);if(selectedObj){selectedObj.scale.setScalar(1.18);setTimeout(()=>selectedObj&&selectedObj.scale.setScalar(1),220)}$('#status-text').textContent='INSPECTING '+btn.querySelector('b').textContent.toUpperCase();setTimeout(()=>$('#status-text').textContent='ARENA ONLINE',1500)})
}
function equipmentPurpose(x,s){const m={Helmet:'Protective headgear engineered for impact management.',Gloves:'Improves protection, grip or sport-specific control.',Shoes:'Provides traction, support and efficient force transfer.',Racket:'Transfers controlled swing speed into the ball or shuttle.',Ball:'The primary object used for passing, striking or scoring.',Net:'Defines the central barrier or scoring structure.',Jersey:'Identifies the athlete or team while supporting movement.'};return m[x]||`${x} is a core piece of ${s} equipment used for performance, control or safety.`}
function wearPurpose(x){return /shoe|boot|cleat/i.test(x)?'Traction, stability and sport-specific foot support.':/helmet|goggle|pad|guard/i.test(x)?'Protective performance equipment for safer movement.':'Lightweight athletic apparel designed for movement and comfort.'}
function filterCategory(cat){activeCategory=cat;$$('.category-chip').forEach(b=>b.classList.toggle('active',b.dataset.category===cat));sportsGroup.children.forEach(g=>{const ok=cat==='All'||g.userData.sport.category===categoryMap[cat];g.userData.filtered=!ok});$('#sport-count').textContent=cat==='All'?SPORTS.length:SPORTS.filter(s=>s.category===categoryMap[cat]).length;playUi(.018,280)}
function openOverlay(which){const sp=$('#search-panel'),hp=$('#help-panel');sp.classList.toggle('open',which==='search');hp.classList.toggle('open',which==='help');sp.setAttribute('aria-hidden',which==='search'?'false':'true');hp.setAttribute('aria-hidden',which==='help'?'false':'true');if(which==='search')setTimeout(()=>$('#search-input').focus(),160)}
function renderSearch(){const q=$('#search-input').value.trim().toLowerCase(),list=SPORTS.filter(s=>!q||s.name.toLowerCase().includes(q)||s.category.toLowerCase().includes(q));$('#search-results').innerHTML=list.map(s=>`<button class="search-result" data-name="${s.name}"><span><b>${s.name}</b><small>${s.category.toUpperCase()}</small></span><i>↗</i></button>`).join('');$$('.search-result').forEach(b=>b.onclick=()=>{const g=sportsGroup.children.find(x=>x.userData.sport.name===b.dataset.name);openOverlay();selectSport(g)})}
function toggleSound(){soundOn=!soundOn;$('#sound-toggle').textContent=soundOn?'◉':'◕';$('#sound-toggle').setAttribute('aria-label',soundOn?'Mute sound':'Enable sound');if(soundOn){audioCtx??=new (window.AudioContext||window.webkitAudioContext)();playUi(.035,620)}}
function playUi(vol=.02,f=360){if(!soundOn)return;audioCtx??=new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*.72,audioCtx.currentTime+.09);g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.11);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.12)}

function updateHover(){if(currentSport||!ready){setHover(null);return}raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(interactive,false),hit=hits.find(h=>!h.object.userData.parentSport.userData.filtered);setHover(hit?hit.object:null)}
function setHover(obj){if(hoverObj===obj)return;if(hoverObj)hoverObj.userData.parentSport.userData.hover=false;hoverObj=obj;if(obj){const g=obj.userData.parentSport;g.userData.hover=true;$('#pointer-label').hidden=false;$('#pointer-label').textContent=g.userData.sport.name.toUpperCase();document.body.style.cursor='pointer'}else{$('#pointer-label').hidden=true;document.body.style.cursor='default'}}
function updateSports(t,dt){sportsGroup.children.forEach((g,i)=>{const filtered=g.userData.filtered,target=filtered?.08:(g.userData.hover?1.18:1),sel=currentSport&&g===selectedObj?1.12:target;g.scale.lerp(new THREE.Vector3(sel,sel,sel),Math.min(1,dt*7));g.position.y=.72+Math.sin(t*1.25+i*.73)*.055;const icon=g.getObjectByName('icon');if(icon){icon.rotation.y+=dt*(g.userData.hover?1.05:.26);if(g.userData.sport.kind==='basketball')icon.position.y=Math.abs(Math.sin(t*2.1+i))*.13}g.userData.beacon.intensity=filtered?.2:(g.userData.hover?14:5.5);const fade=currentSport&&g!==selectedObj?.18:1;g.traverse(o=>{if(o.material&&'opacity' in o.material){o.material.transparent=fade<1||o.material.transparent;o.material.opacity=Math.max(.08,fade)}})})}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;updateHover();updateSports(t,dt);if(!controls.enabled){camera.position.lerp(desiredCam,1-Math.pow(.001,dt));controls.target.lerp(cameraTarget,1-Math.pow(.0015,dt))}else if(!currentSport)controls.target.lerp(cameraTarget,.05);if(!reducedMotion&&!currentSport&&controls.enabled)sportsGroup.rotation.y=Math.sin(t*.08)*.035;scene.children.forEach(o=>{if(o.userData.particles)o.rotation.y=t*.007});controls.update();renderer.render(scene,camera)}
function onResize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width: 900px)').matches?1.35:2))}
